name: check whoami
on:
  workflow_dispatch:
jobs:
  performance_test:
    runs-on: ecs-pt-runner

    steps:
      - name: who am I?
        run: |
          whoami 

      - name: who am I?
        run: |
          sudo su 

      - name: who am I?
        run: |
          whoami
