# name: Performance Testing

# on:
#   push:

# jobs:
#   performance_test:
#     runs-on: self-hosted
#     env:
#       JMETER_THREADS: 10
#       JMETER_DURATION: 60
#       JMETER_HOME: 'C:\apache-jmeter-5.6.3'
#       WORKING_DIRECTORY: 'Performance'
#       PYTHON_HOME: 'C:\actions-runner\_work\_tool\Python\3.9.13\x64'
      
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
      
#       - name: Replace Password values
#         run: |
#            sed -i "s|passwordwhichneedstobechanged|${{ secrets.CYPRESS_SSO_PASSWORD }}|" welltracker1.jmx          
#         working-directory: ${{ env.WORKING_DIRECTORY }}

#       - name: Print GitHub Workspace
#         run: |
#           echo "GitHub Workspace: ${{ github.workspace }}"

#       - name: Print Working Directory
#         run: |
#           echo "Working Directory: ${{ env.WORKING_DIRECTORY }}"

#       - name: Clear JTL file
#         run: |
#           $env:JMETER_RESULT="$GITHUB_WORKSPACE\${{ env.WORKING_DIRECTORY }}\result.jtl"
#           Clear-Content -Path $env:JMETER_RESULT

#       - name: Run Performance Tests
#         run: |
#           $env:JMETER_SCRIPT="$GITHUB_WORKSPACE\${{ env.WORKING_DIRECTORY }}\filename.jmx"
#           $env:JMETER_RESULT="$GITHUB_WORKSPACE\${{ env.WORKING_DIRECTORY }}\result.jtl"
#           & "$env:JMETER_HOME\bin\jmeter.bat" -Jthreads=${{ env.JMETER_THREADS }} -Jloadtime=${{ env.JMETER_DURATION }} -n -t "$env:JMETER_SCRIPT" -l "$env:JMETER_RESULT" -e -o "$env:GITHUB_WORKSPACE\${{ env.WORKING_DIRECTORY }}\html-reports"
          
#       - name: Upload JMeter Test Results
#         uses: actions/upload-artifact@v3
#         if: always()  
#         with:
#           name: perf_test_results
#           path: |
#             ${{ env.JMETER_RESULT }}
#             ${{ github.workspace }}\${{ env.WORKING_DIRECTORY }}\html-reports